{
  config,
  lib,
  pkgs,
  ...
}:

let
  cfg = config.services.pods.nextcloud;

  # Auto-assign ports by account index (attrsets are sorted alphabetically by key, stable ordering)
  # Index 0: IMAP 1143, SMTP 1025, CalDAV 1080, LDAP 1389
  # Index 1: IMAP 1243, SMTP 1125, CalDAV 1180, LDAP 1489
  # Index N: base + (N * 100)
  indexedAccounts = lib.imap0 (
    i: { name, value }: {
      inherit name;
      tenantId = value.tenantId;
      idx = i;
    }
  ) (lib.attrsToList cfg.davmail.accounts);
in
{
  options.services.pods.nextcloud.davmail._configFiles = lib.mkOption {
    type = lib.types.attrsOf lib.types.package;
    internal = true;
    default = builtins.listToAttrs (
      map (acct: {
        name = acct.name;
        value = pkgs.writeText "davmail-${acct.name}.properties" ''
          # DavMail gateway configuration for account: ${acct.name}
          # Generated by NixOS — do not edit manually

          # Server mode (no GUI)
          davmail.server=true

          # Office 365 with OAuth2 device code flow (supports MFA including TOTP)
          davmail.mode=O365Modern
          davmail.url=https://outlook.office365.com/EWS/Exchange.asmx

          # Use Microsoft's own Office desktop public client — no app registration or
          # admin consent required. This client supports OAuth2 device code flow so
          # DavMail prints a login URL + code to logs on first connect; authenticate
          # in a browser with full MFA, token is then cached for ~90 days.
          davmail.oauth.clientId=d3590ed6-52b3-4102-aeff-aad2292ab01c

          # "Out of band" redirect URI signals device code flow to the OAuth2 server
          davmail.oauth.redirectUri=urn:ietf:wg:oauth:2.0:oob

          # Restrict to this specific Azure AD tenant
          davmail.oauth.tenantId=${acct.tenantId}

          # Persist OAuth tokens across container restarts
          davmail.oauth.tokenFilePath=/data/oauth-tokens.json

          # Allow connections from other containers in the same pod
          davmail.allowRemote=true

          # Protocol ports (auto-assigned by account index: base + idx * 100)
          davmail.imapPort=${toString (1143 + acct.idx * 100)}
          davmail.smtpPort=${toString (1025 + acct.idx * 100)}
          davmail.caldavPort=${toString (1080 + acct.idx * 100)}
          davmail.ldapPort=${toString (1389 + acct.idx * 100)}
          davmail.popPort=

          # Logging to stdout (integrates with podman logs / journald)
          # Required: OAuth2 device code flow URL appears at INFO level —
          # watch "podman logs -f nextcloud-davmail-${acct.name}" after first
          # connection attempt to get the authentication URL and code.
          davmail.logFilePath=/dev/stdout

          # Log levels (DavMail uses Log4j-style syntax, not Log4j2)
          # Temporarily DEBUG to diagnose OAuth flow — revert to INFO once working
          log4j.logger.davmail=DEBUG
          log4j.logger.org.apache=WARN
          log4j.logger.httpclient=WARN

          # Disable update check (no GUI, may be firewalled)
          davmail.disableUpdateCheck=true

          # No TLS on IMAP/SMTP/CalDAV/LDAP — intentional: all traffic is
          # pod-internal loopback (127.0.0.1). Never expose these ports to the
          # network without adding TLS first.
        '';
      }) indexedAccounts
    );
    description = "Generated davmail.properties config files, keyed by account name";
  };

  options.services.pods.nextcloud.davmail._indexedAccounts = lib.mkOption {
    type = lib.types.listOf lib.types.anything;
    internal = true;
    default = indexedAccounts;
    description = "Accounts with pre-computed port indices, for use in pod-nextcloud.nix";
  };
}
