# SOPS Configuration File
keys:
  # Your personal age key (stored in 1Password)
  # For local encryption/decryption
  - &personal age17xvxtg5me0cqeaecfsdtver2p84hnvxw9deftwr5dq2vhu2j0g3snp0fqz

  # Chestnut server - age key
  - &chestnut age1zqgtk82eu8mre77q39un2vqvcnxg5twu858tph07gaat7jxzvggqdn06jk

creation_rules:
  # Chestnut server secrets
  - path_regex: hosts/chestnut/secrets\.yaml$
    key_groups:
      - age:
          - *personal
          - *chestnut
