# SOPS Configuration File
keys:
  # Your personal age key (stored in 1Password)
  # For local encryption/decryption
  - &personal age17xvxtg5me0cqeaecfsdtver2p84hnvxw9deftwr5dq2vhu2j0g3snp0fqz

  # Chestnut server - age key
  - &chestnut age10htej2jts7xx8hhcaz4fh9r96czhg7dfznlldlrzj08vpfjcv4js4d3hp5

  # Nutcracker server - age key
  - &nutcracker age1uag9znk7atpgx8mjdyvczj4fy203gg9le82u9ljx7hp9cwgunsgslz2t3u

  # Hazelnut Lattepanda - age key
  - &hazelnut age1nfedn87d4vznulenxj37v7vaja9aa50zpm8st585gxuknm4vrpxqrhspmd

creation_rules:
  - path_regex: hosts/chestnut/secrets\.yaml$
    key_groups:
      - age:
        - *personal
        - *chestnut
        - *hazelnut

  - path_regex: hosts/nutcracker/secrets\.yaml$
    key_groups:
      - age:
        - *personal
        - *nutcracker

  - path_regex: hosts/hazelnut/secrets\.yaml$
    key_groups:
      - age:
        - *personal
        - *hazelnut
